
site_name: Repository Documentation
site_url: https://tu-graz-library.github.io/docs-repository
site_description: Repository Documentation
site_author: 'Mojib Wali'

# uncomment to show the github icon in the header with
# number of forks & stars
# repo_url: https://github.com/tu-graz-library/docs-repository
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2020-2021 Graz University of Technology'

theme:
  highlightjs: true
  features:
    - navigation.tabs
  name: material
  custom_dir: 'overrides'
  palette:
    primary: 'white'
  font:
    text: 'Open Sans'
    code: 'Roboto Mono'
  logo: 'images/tug_logo.png'
  favicon: 'images/favicon.ico'


nav:
  - Home: 'index.md'
  - Deployment:
    - Infrastructure: 'deployment/index.md'
    - Production instance: 'deployment/production.md'
    - Test Instance: 'deployment/test.md'
    - Development instance: 'deployment/dev.md'
    - Deploy : 'deployment/deploy.md'
    - VMs : 'deployment/vms.md'
  - Services:
    # - Development services: 'services/index.md'
    - pgAdmin: 'services/pgadmin.md'
  - Configs:
    - Configurations: 'configs/index.md'
    - Gitlab Runner: 'configs/gitlab-runner.md'
    - PostgreSQL: 'configs/postgresql.md'
    - SSH-key: 'configs/sshkey.md'
    - CEPH: 'configs/ceph.md'
    - Override Pages: 'configs/override-pages.md'
  - Datamodel:
    - Overview: 'datamodel/index.md'
    - Various Possibilities: 'datamodel/various_possibilities.md'
    - Custom Fields: 'datamodel/custom_fields.md'
    - Master Format: 'datamodel/master_format.md'
    - Independent Data Model: 'datamodel/independent_data_model.md'
    - Dependent Data Model: 'datamodel/dependent_data_model.md'

# Customization
extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: 'https://github.com/tu-graz-library/docs-repository'
extra_css:
  - stylesheets/custom.css

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
